---
- name: Save Config IOS
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Save config IOS
      ios_command:
        commands:
          - write memory
      register: output

    - debug: var=output.stdout_lines