---
- name: Run cisco commands
  hosts: Cisco_IOS
  connection: local
  gather_facts: false

  tasks:

    - name: get base information
      ios_command:
        commands:
          - show version | include IOS
          - show ip interface brief
      register: output

    - debug: var=output.stdout_lines