---
- name: Show version IOS
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Show version IOS
      ios_command:
        commands:
          - show version | include IOS
      register: output

    - debug: var=output.stdout_lines