---
  - name: Show version Cisco
    hosts: all
    gather_facts: no
    connection: local

    # this is for the IOS Module provider
    vars:
      cli:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli

    tasks:
      # Collect all facts from the device - this helps set the hostname
      - ios_facts:
          gather_subset:
              - config
          provider: "{{ cli }}"

      # Network To Code module to grab inventory data
      - name: show version
        ntc_show_command:
          connection: "{{ connection }}"
          platform: "{{ platform }}"
          port: "{{ port }}"
          command: 'show ver'
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
        register: results

      - debug: var=results.response